- name: Disparar workflow no Tower/AAP
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Launch workflow and wait until finished
      awx.awx.workflow_launch:
        tower_host: "{{ tower_host }}"
        tower_oauth_token: "{{ tower_oauth_token }}"
        validate_certs: false
        workflow_job_template: "{{ workflow_id }}"
        extra_vars: "{{ extra_vars }}"
        wait: true # aguarda até terminar
        timeout: 60 # segundos
      register: wf_result

    - name: Mostrar resumo do workflow
      ansible.builtin.debug:
        var: wf_result

# - name: Lançar workflow via API Tower
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - name: Launch workflow job (API)
#       ansible.builtin.uri:
#         url: "{{ tower_host }}/api/controller/v2/workflow_job_templates/{{ workflow_id }}/launch/"
#         method: POST
#         headers:
#           Authorization: "Bearer {{ tower_oauth_token }}"
#           Content-Type: "application/json"
#         body_format: json
#         body:
#           extra_vars: "{{ extra_vars }}"
#         status_code:
#           - 201
#           - 202
#       register: api_launch

#     - name: Mostrar retorno da API
#       ansible.builtin.debug:
#         var: api_launch.json

# fetch("https://sandbox-aap-wcardozo-dev.apps.rm3.7wse.p1.openshiftapps.com/api/controller/v2/workflow_job_templates/10/launch/", {
#   "headers": {
#     "accept": "*/*",
#     "accept-language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
#     "accepts": "application/json",
#     "content-type": "application/json",
#     "sec-ch-ua": "\"Chromium\";v=\"142\", \"Microsoft Edge\";v=\"142\", \"Not_A Brand\";v=\"99\"",
#     "sec-ch-ua-mobile": "?0",
#     "sec-ch-ua-platform": "\"Windows\"",
#     "sec-fetch-dest": "empty",
#     "sec-fetch-mode": "cors",
#     "sec-fetch-site": "same-origin",
#     "x-csrftoken": "fKtfggzM63lyXRUjvxFvGWXKwo7bTfaq"
#   },
#   "referrer": "https://sandbox-aap-wcardozo-dev.apps.rm3.7wse.p1.openshiftapps.com/execution/templates/workflow-job-template/10/details",
#   "body": "{}",
#   "method": "POST",
#   "mode": "cors",
#   "credentials": "include"
# });
