# - name: Disparar workflow no Tower/AAP
#   hosts: localhost
#   gather_facts: false

#   tasks:
#     - name: Launch workflow and wait until finished
#       awx.awx.workflow_launch:
#         name: "10"
#         controller_host: "{{ controller_host }}"
#         controller_oauthtoken : "{{ controller_oauthtoken  }}"
#         # validate_certs: false
#         # workflow_job_template: "{{ workflow_id }}"
#         # extra_vars: "{{ extra_vars }}"
#         # wait: true # aguarda até terminar
#         timeout: 60 # segundos
#       register: wf_result

#     - name: Mostrar resumo do workflow
#       ansible.builtin.debug:
#         var: wf_result

- name: Lançar workflow via API Tower
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "https://sandbox-aap-wcardozo-dev.apps.rm3.7wse.p1.openshiftapps.com"
    controller_oauthtoken: IKq1VQCJcCRPz8butUWVDb1HWGdiSC
    workflow_id: 10 # id ou nome do workflow template
    timeout: 60
    poll_interval: 5
    extra_vars:
      # vars opcionais para o workflow
      env: dev
  tasks:
    - name: Launch workflow job (API)
      ansible.builtin.uri:
        url: "{{ controller_host }}/api/controller/v2/workflow_job_templates/{{ workflow_id }}/launch/"
        method: POST
        headers: &header
          Authorization: "Bearer {{ controller_oauthtoken }}"
          Content-Type: "application/json"
        body_format: json
        body:
          extra_vars: "{{ extra_vars }}"
        status_code: &status_code
          - 201
          - 202
      register: api_launch

    - name: Mostrar retorno da API
      ansible.builtin.debug:
        var: api_launch.json

    - name: Wait until workflow finishes
      vars:
        finished_states:
          - "successful"
          - "failed"
          - "error"
          - "canceled"
      ansible.builtin.uri:
        headers: *header
        url: "{{ controller_host }}{{ api_launch.json.url }}/"
        method: GET
        status_code: *status_code
      register: wf_status
      retries: "{{ (timeout / poll_interval) | int }}"
      delay: "{{ poll_interval }}"
      until: wf_status.json.status in finished_states

    - name: Display final result
      ansible.builtin.debug:
        msg: "Workflow {{ api_launch.json.id }} finalizado com status: {{ wf_status.json.status }}"
